### ISSUE TITLE
Pesquisa por usuários busca somente no campo Username ou Usuário

### ISSUE THREAD

**Issue by suelisuga** [bireme/accounts#1]
Ao clicar menu Usuários e realizar buscas por nomes, o único campo buscado é Username/Usuário.

Ex: ao pesquisar pelo nome Heitor, recuperou apenas o registro com username Heitor e e-mail barbieri@paho.org, porém esse usuario tem também username Barbieri e e-mail barbieri@bireme.ops-oms.org

Seria ideal buscar por palavras presentes nos outros campos Username e E-mail.

Obrigada!

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
A pesquisa agora é realizada nos campos de username e email, implementado em #16.
