### ISSUE TITLE
Erro em nova instalação (INFOMED) para superuser

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/accounts#13]
O sistema retorna erro para condição de acesso do superuser (admin) e a base de usuários esta vazia.

**Comment by viniciusandrade** [comment]
Correção aplicada em https://github.com/bireme/accounts/commit/1b1fd61cc2ef63d1e0b5e9fdb647f5ec6a3c955b

**Comment by Humberto-L** [comment]
A barra de menu das opcoes File Edit View Repository Branch Help nao aparece.
