### ISSUE TITLE
Accounts não está retornando resultado de busca por CC

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/accounts#16]
Antes, quando todos os usuários ficavam numa única página, ainda era possível fazer a busca utilizando <Ctrl+F>. Agora, é inviável fazer isso em 27 páginas!

A busca só retorna quando fazemos a busca por nome de usuário. Se tentamos uma parte do e-mail ou CC, ela não retorna resultados, e realizamos muito mais buscas nesse sentido (descobrir quem são os usuários de determinado CC ou se o CC possui usuários cadastrados), que ao inverso (descobrir qual o CC de determinado usuário).

![image](https://user-images.githubusercontent.com/47643830/66592683-ee16a400-eb6b-11e9-9939-9c220f9d20cc.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

O Ronaldo adicionou um filtro por centro cooperante e também a possibilidade de busca por email no formulário. 
Esta implementação esta disponível no ambiente de testes do Accounts, por favor, quando possível favor realizar os testes e também simular o acesso ao Accounts por usuários avançados para verificar se não teve algum efeito colateral. Obrigado.

**Comment by viniciusandrade** [comment]
OK, você consegue simular o acesso de um outro usuário avançado que esteja associado a um centro que coordena mais de uma rede para verificar se a lista é apresentada para ele também?

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula, OK obrigado pela validação vou atualizar o Accounts em produção com este recurso. 
Relacionado as diferenças entre os ambientes não vejo problema pois em alguns casos precisamos alterar dados no teste para simular alguma situação então é normal essas diferenças.

Obrigado
