### ISSUE TITLE
Incluir pesquisa por país no BIREME Accounts

### ISSUE THREAD

**Issue by suelisuga** [bireme/accounts#21]
Prezados,

É comum a pesquisa por todos os usuários existentes em um país. Atualmente essa pesquisa não funciona bem.

Sugiro usar os dois primeiros digitos do código do Centro cooperante para formar o nome/sigla do país.
![image](https://user-images.githubusercontent.com/13105683/67983351-45f07a00-fc03-11e9-8f16-7a1e04d4e0f7.png)

**Comment by viniciusandrade** [comment]
@suelisuga / @AngelicaSAPaula 

Ajuste disponível no ambiente de testes do Accounts favor validar para integração na produção.

Obrigado

**Comment by suelisuga** [comment]
@viniciusandrade e @rfdeoliveira o filtro de país aparece na instancia de teste e apesar de existir a tradução para PT, EN e ES. na lista aparece somente no idioma inglês.

Dúvida: é possível colocar todos os países da AL&C na frente na lista e deixar os países do resto do mundo depois da lista AL&C?

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

A lista de paises do Accounts não possue o atributo que define que o país pertence a AL&C, desta forma não tem como alterar a ordem.

@rfdeoliveira, para a questão de tradução favor verifica se a implementação realizada no FI-ADMIN (https://github.com/bireme/fi-admin/blob/master/bireme/utils/models.py#L89) se aplica neste contexto.

Obrigado

**Comment by viniciusandrade** [comment]
@suelisuga / @AngelicaSAPaula

Tradução aplicada no filtro de países. Favor validar para aplicarmos em produção. Obrigado.

**Comment by viniciusandrade** [comment]
Infelizmente não pois são filtros independentes. 

Estando OK em teste estou fechando para atualização em produção. Obrigado.
