### ISSUE TITLE
Link para ativação da senha com erro

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/accounts#36]
@viniciusandrade após a última modificação, os novos usuários relatam que, ao clicar no link para ativação de senha e serem direcionados ao Accounts, aparece esta mensagem:

![image](https://user-images.githubusercontent.com/47643830/160880501-34c701ba-7a5a-4416-9c4d-bcc869f62dd4.png)

Então, não conseguem sair deste passo, sem poder ativar a senha e dar início aos registros no Fi-Admin.

**Comment by AngelicaSAPaula** [comment]
Acredito que não esteja habilitada neste repositório, pois não consigo assinalar nada na coluna à direita!

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula se não me engano isso acontece porque o link de ativação tem um prazo para funcionar ... desta forma se o usuário recebe o email e só clica no dia seguinte ou após algumas horas o link é inválido e ele não consegue prosseguir ... teria que clicar na opção de enviar novamente o email de confirmação para ele receber um novo link.

**Comment by AngelicaSAPaula** [comment]
@viniciusandrade muito obrigada! Vou encerrar o issue e, caso tenhamos alguma reclamação que não for solucionada, volto a abrir!
