### ISSUE TITLE
Ativação de código 

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/accounts#37]
@viniciusandrade  Favor ativar o código BR2717.9 para criação de usuário no Accounts

**Comment by suelisuga** [comment]
@viniciusandrade estamos transformando BR1487.1 de UP para CC. Poderia verificar processamento necessário para  atualização e entrada no BIREME Accounts?

Obrigada!

Sueli

**Comment by viniciusandrade** [comment]
Os códigos **BR2717.9** e **BR1487.1** foram importados para o BIREME Accounts.

Obrigado @anakatiacamilo pelo processamento.
