### ISSUE TITLE
Alfabetar códigos de CC na lista de Redes

### ISSUE THREAD

**Issue by suelisuga** [bireme/accounts#8]
Solicito colocar a lista de CC presente em Rede em ordem alfabética.
Imagino que ao colocar em ordem alfabética, no ato da digitação o código seja "automaticamente" apresentado, assim como ocorre com outras listas.

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/accounts/commit/596956444f08a23d6aceca2937a79c7c6db59297

**Comment by suelisuga** [comment]
obrigada!
